[package]
name = "bpd_engine"
description = "owns debuggee processes and the control plane to their agents"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
bpd_core = { workspace = true }
bpd_protocol = { workspace = true }

getrandom = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bpd_test = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
