# generated by `by run` — runs the target module with .by-aware tracebacks
import dis
import hashlib
import importlib.machinery
import importlib.util
import linecache
import os
import sys
import traceback
import types
import warnings

from _by_sourcemap import DIGESTS, SOURCEMAP

# index the sourcemap by realpath so symlinked temp dirs (e.g. /tmp on macOS)
# still match the filenames python reports in frames. the key the entry was
# written under travels with it, because DIGESTS is keyed the unresolved way
_BY_MAP = {os.path.realpath(py): (py, info) for py, info in SOURCEMAP.items()}
# the .by files themselves, which a module compiled by `_by_code` names in its frames,
# with the key of the entry each was transpiled under
_BY_SOURCES = {os.path.realpath(info[0]): py for py, info in SOURCEMAP.items()}

# this file, whose frames are never the program's
_RUNNER = os.path.realpath(__file__)

# entries already checked against their digests, so each file is read at most
# once no matter how many frames it contributes
_CURRENT = set()
_STALE = set()


def _digest_matches(path, spec):
    # the algorithm is named in the value, so one this reader does not know is a
    # refusal rather than hex it could never have produced
    algorithm, _, expected = spec.partition(":")
    try:
        digest = hashlib.new(algorithm)
    except ValueError:
        return False
    try:
        with open(path, "rb") as handle:
            for chunk in iter(lambda: handle.read(65536), b""):
                digest.update(chunk)
    except OSError:
        return False
    return digest.hexdigest() == expected


def _stale(key, by_path):
    _STALE.add(key)
    sys.stderr.write(
        f"note: {by_path} no longer matches what it was transpiled from, "
        "so no frame names a line of it\n"
    )


def _is_current(key, by_path):
    # the map describes a *pair* of files, and a .by line read out of it is only
    # true while both are still the ones it was built from. a source saved since
    # the transpile would otherwise be quoted at line numbers belonging to the
    # file it replaced — a wrong answer, where leaving the frame generated is
    # merely a worse one
    if key in _CURRENT:
        return True
    if key in _STALE:
        return False
    digests = DIGESTS.get(key)
    if (
        digests is not None
        and _digest_matches(by_path, digests["by"])
        and _digest_matches(key, digests["py"])
    ):
        _CURRENT.add(key)
        return True
    _stale(key, by_path)
    return False


def _still_current(key, by_path):
    # a module `_by_code` compiled has its `.by` lines in its frames already, checked
    # when it was loaded. a `.by` saved over since then no longer has those lines, so
    # it is checked again before a frame names one
    if key in _STALE:
        return False
    digests = DIGESTS.get(key)
    if digests is not None and _digest_matches(by_path, digests["by"]):
        return True
    _stale(key, by_path)
    return False


def _rewrite(frames):
    # drop the runner/runpy bootstrap above the first user frame
    first = next(
        (
            i
            for i, f in enumerate(frames)
            if os.path.realpath(f.filename) in _BY_MAP
            or os.path.realpath(f.filename) in _BY_SOURCES
        ),
        None,
    )
    if first is not None:
        # below the program's first frame, the runner's own are the loader it puts on
        # every staged module, which a frame of the program never called
        frames = [f for f in frames[first:] if os.path.realpath(f.filename) != _RUNNER]
    out = []
    for f in frames:
        compiled_from = _BY_SOURCES.get(os.path.realpath(f.filename))
        if compiled_from is not None and not _still_current(compiled_from, f.filename):
            # its line is one of the file that was transpiled, which is gone. the
            # generated line it came from is named instead when it is the only one
            # that `.by` line was written as, and no line at all when it is not
            _, generated = SOURCEMAP[compiled_from]
            written_as = [
                index + 1
                for index, line in enumerate(generated)
                if f.lineno and line == f.lineno - 1
            ]
            if len(written_as) == 1:
                out.append(traceback.FrameSummary(compiled_from, written_as[0], f.name))
            else:
                out.append(f'  File "{f.filename}", in {f.name}\n')
            continue
        entry = _BY_MAP.get(os.path.realpath(f.filename))
        if entry is not None and f.lineno is not None:
            key, (by_path, lines) = entry
            idx = f.lineno - 1
            mapped = lines[idx] if 0 <= idx < len(lines) else None
            if mapped is not None and _is_current(key, by_path):
                by_lineno = mapped + 1
                text = linecache.getline(by_path, by_lineno).strip() or f.line
                out.append(
                    traceback.FrameSummary(by_path, by_lineno, f.name, line=text)
                )
                continue
        out.append(f)
    return out


def _excepthook(etype, evalue, tb):
    frames = _rewrite(traceback.extract_tb(tb))
    if (
        isinstance(evalue, SyntaxError)
        and evalue.filename is not None
        and os.path.realpath(evalue.filename) in _BY_SOURCES
        and all(
            isinstance(frame, traceback.FrameSummary)
            and os.path.realpath(frame.filename) == _RUNNER
            for frame in frames
        )
    ):
        # the program's own module, which the runner could not compile: every frame
        # is the runner's, so it is reported as python reports a script it cannot
        # compile, by where the error is and nothing above it
        sys.stderr.write("".join(traceback.format_exception_only(etype, evalue)))
        return
    sys.stderr.write("Traceback (most recent call last):\n")
    # a frame `_rewrite` could only name is already text. the others are formatted a
    # run at a time, so python still folds a repeated one
    run = []
    for frame in frames + [None]:
        if isinstance(frame, traceback.FrameSummary):
            run.append(frame)
            continue
        sys.stderr.write("".join(traceback.StackSummary.from_list(run).format()))
        run = []
        if frame is not None:
            sys.stderr.write(frame)
    sys.stderr.write("".join(traceback.format_exception_only(etype, evalue)))


def _by_source_of(origin):
    # the .by file a staged .py was transpiled from, or None for anything else —
    # a hand-written .py carried over verbatim, or a module from site-packages
    if not origin:
        return None
    entry = _BY_MAP.get(os.path.realpath(origin))
    return None if entry is None else entry[1][0]


def _varint(out, value):
    while value >= 64:
        out.append(0x40 | (value & 63))
        value >>= 6
    out.append(value)


def _svarint(out, value):
    _varint(out, (-value << 1) | 1 if value < 0 else value << 1)


def _relined(code, filename, by_line, width):
    """`code` and every code object it holds, named `filename`, with each location
    moved to the line `by_line` gives, spanning the whole of that line.

    The line table's format is private to each python version: see `Objects/locations.md`
    (3.11 on) and `Objects/lnotab_notes.txt` (3.10, and 3.9 before it) in cpython.
    """
    consts = tuple(
        _relined(const, filename, by_line, width)
        if isinstance(const, types.CodeType)
        else const
        for const in code.co_consts
    )
    first = by_line(code.co_firstlineno)
    table = bytearray()
    if sys.version_info >= (3, 11):
        # an entry for each run of up to 8 code units at one line, in the long form,
        # which holds any line and column, or the form for no location
        lines = [
            None if line is None else by_line(line) for line, *_ in code.co_positions()
        ]
        previous = first
        start = 0
        while start < len(lines):
            line = lines[start]
            end = start + 1
            while end < len(lines) and end - start < 8 and lines[end] == line:
                end += 1
            if line is None:
                table.append(0x80 | (15 << 3) | (end - start - 1))
            else:
                table.append(0x80 | (14 << 3) | (end - start - 1))
                _svarint(table, line - previous)
                _varint(table, 0)
                _varint(table, 1)
                _varint(table, width(line) + 1)
                previous = line
            start = end
        return code.replace(
            co_filename=filename,
            co_firstlineno=first,
            co_consts=consts,
            co_linetable=bytes(table),
        )
    if sys.version_info >= (3, 10):
        # a (bytecode length, line delta) pair for each range, -128 for no line
        previous = first
        for start, end, line in code.co_lines():
            size = end - start
            delta = -128
            if line is not None:
                line = by_line(line)
                delta = line - previous
                previous = line
                while delta > 127:
                    table += bytes((0, 127))
                    delta -= 127
                while delta < -127:
                    table += bytes((0, 256 - 127))
                    delta += 127
            while size > 254:
                table += bytes((254, delta & 255))
                delta = -128 if line is None else 0
                size -= 254
            table += bytes((size, delta & 255))
        return code.replace(
            co_filename=filename,
            co_firstlineno=first,
            co_consts=consts,
            co_linetable=bytes(table),
        )
    # a (bytecode offset delta, line delta) pair for each place the line changes
    offset, previous = 0, first
    for start, line in dis.findlinestarts(code):
        line = by_line(line)
        step, delta = start - offset, line - previous
        while step > 255:
            table += bytes((255, 0))
            step -= 255
        while delta > 127:
            table += bytes((step, 127))
            step, delta = 0, delta - 127
        while delta < -128:
            table += bytes((step, 128))
            step, delta = 0, delta + 128
        table += bytes((step, delta & 255))
        offset, previous = start, line
    return code.replace(
        co_filename=filename,
        co_firstlineno=first,
        co_consts=consts,
        co_lnotab=bytes(table),
    )


def _by_code(origin):
    """The staged `.py` at `origin` compiled as the `.by` it was transpiled from.

    A program reads its own locations back — `traceback.format_exc()`, the file
    and line `warnings` attributes a warning to, `co_filename`, `inspect` — and
    python answers each from the code object. So the code object is named after
    the `.by` path, with every line the `.by` line it came from: the answer is then
    the author's wherever it is read, and the source line python shows beside it is
    read from the `.by` too. A line the transpiler wrote on its own — a runtime
    helper — has no `.by` line, and says so as line 0. Columns are the generated
    file's, so every location spans the whole of its `.by` line instead: python
    marks no part of a line a location covers, and reads what it can from the `.by`
    text.

    The `.py` is compiled from its text, as python's own loader would, and only
    then moved to the `.by`: python 3.9 to 3.11 refuse, at the interpreter's
    recursion limit, a syntax tree nested deeper than the source they accept. A
    warning the compiler raises is moved to its `.by` line the same way, and so is
    the `SyntaxError` it raises for one the warning filters make an error.

    `None` when there is no `.by` to answer with, or it has changed since it was
    transpiled, which leaves the module to python's own loader.
    """
    entry = _BY_MAP.get(os.path.realpath(origin)) if origin else None
    if entry is None:
        return None
    key, (by_path, lines) = entry
    if not _is_current(key, by_path):
        return None
    with open(origin, "rb") as handle:
        source = handle.read()
    with open(by_path, "rb") as handle:
        widths = [len(line.rstrip(b"\r\n")) for line in handle]

    def by_line(line):
        mapped = (
            lines[line - 1] if line is not None and 0 < line <= len(lines) else None
        )
        return 0 if mapped is None else mapped + 1

    def width(line):
        return widths[line - 1] if 0 < line <= len(widths) else 0

    with warnings.catch_warnings(record=True) as caught:
        try:
            code = compile(source, origin, "exec", dont_inherit=True)
        except SyntaxError as error:
            # a warning the filters turn into an error (`-W error`) is raised by the
            # compiler as a `SyntaxError` at the line it would have warned about, so
            # it is moved to the `.by` like the warning. its columns are the
            # generated file's, which is why it points at no part of the line
            line = by_line(error.lineno) if error.filename == origin else 0
            if line == 0:
                raise
            text = linecache.getline(by_path, line) or None
            raise SyntaxError(error.msg, (by_path, line, None, text)) from None
    for warning in caught:
        if warning.filename == origin:
            warnings.warn_explicit(
                warning.message, warning.category, by_path, by_line(warning.lineno)
            )
        else:
            warnings.warn_explicit(
                warning.message, warning.category, warning.filename, warning.lineno
            )
    return _relined(code, by_path, by_line, width)


class _ByLoader:
    """Wraps a staged module's loader to name its `.by` source as `__file__`.

    The program is run out of a directory of transpiled copies, so every path
    python derives from a module's origin — `__file__`, and anything a tool walks
    up from it to find — names a temporary file in a directory that is deleted
    when the run ends. The `.by` the module was written as is the answer to every
    question those paths are asked, so it is what the module reports.

    A module python's own loader would compile is compiled by `_by_code` instead,
    under the `.by` path and lines. One any other loader stands behind — a test
    runner that rewrites assertions as it compiles — is left to it, and only its
    `__file__` moves; its frames are rewritten to `.by` lines when they reach the
    excepthook.
    """

    def __init__(self, inner, by_path):
        self._by_inner = inner
        self._by_path = by_path

    def create_module(self, spec):
        return self._by_inner.create_module(spec)

    def get_code(self, fullname):
        if type(self._by_inner) is importlib.machinery.SourceFileLoader:
            code = _by_code(self._by_inner.get_filename(fullname))
            if code is not None:
                return code
        return self._by_inner.get_code(fullname)

    def exec_module(self, module):
        module.__file__ = self._by_path
        if type(self._by_inner) is importlib.machinery.SourceFileLoader:
            code = _by_code(self._by_inner.get_filename(module.__name__))
            if code is not None:
                exec(code, module.__dict__)
                return
        self._by_inner.exec_module(module)

    def __getattr__(self, name):
        return getattr(self._by_inner, name)


class _ByFinder:
    """Puts a `_ByLoader` on every staged module, whoever ends up finding it."""

    def find_spec(self, fullname, path=None, target=None):
        for finder in sys.meta_path:
            if finder is self:
                continue
            find = getattr(finder, "find_spec", None)
            if find is None:
                continue
            spec = find(fullname, path, target)
            if spec is None:
                continue
            by_path = _by_source_of(getattr(spec, "origin", None))
            if by_path is not None and spec.loader is not None:
                spec.loader = _ByLoader(spec.loader, by_path)
            return spec
        return None


def _entry_spec(module):
    """The spec whose code `by run <module>` should execute.

    A package is run through its `__main__` submodule, the way `python -m` does:
    the package's own `__init__` is what an *import* of it runs, and running that
    instead would execute the wrong file and never reach the program.
    """
    spec = importlib.util.find_spec(module)
    if spec is None:
        raise ImportError("No module named " + repr(module), name=module)
    if spec.submodule_search_locations is not None:
        module = module + ".__main__"
        try:
            spec = importlib.util.find_spec(module)
        except ImportError as exc:
            raise ImportError(
                repr(module) + " is a package and cannot be directly executed",
                name=module,
            ) from exc
        if spec is None:
            raise ImportError(
                repr(module) + " is a package and cannot be directly executed",
                name=module,
            )
    if spec.loader is None:
        raise ImportError("module " + repr(module) + " has no loader", name=module)
    return module, spec


def _run_as_main(module):
    """Run `module` as `__main__`, with `.by` paths for `__file__` and `argv[0]`.

    `runpy.run_module` fetches the entry module's code straight from its loader
    rather than executing it through one, so the loader wrapper that fixes every
    imported module never sees this one. Its few lines are spelled out here
    instead, which is also the only place `sys.argv[0]` can be set: `alter_sys`
    would otherwise overwrite it with the staged path on the way in.
    """
    module, spec = _entry_spec(module)
    code = spec.loader.get_code(module)
    if code is None:
        raise ImportError("module " + repr(module) + " has no code to run", name=module)
    by_path = _by_source_of(spec.origin) or spec.origin
    sys.argv[0] = by_path
    main_module = types.ModuleType("__main__")
    main_module.__file__ = by_path
    main_module.__loader__ = spec.loader
    main_module.__package__ = spec.parent
    # the real spec, which is what `runpy` puts here too. it has to name the
    # module rather than be left unset: `multiprocessing`'s spawn start method —
    # the default on macos and windows — reads `__spec__.name` to tell the child
    # what to re-import, and falls back to running `__file__` as a *path* when
    # there is none. that path is now the `.by`, which python cannot compile, so
    # leaving this unset broke every spawned child
    main_module.__spec__ = spec
    sys.modules["__main__"] = main_module
    exec(code, main_module.__dict__)


def main():
    sys.excepthook = _excepthook
    sys.meta_path.insert(0, _ByFinder())
    module = sys.argv[1]
    sys.argv = sys.argv[1:]
    try:
        _run_as_main(module)
    except SystemExit:
        raise
    except BaseException:
        sys.excepthook(*sys.exc_info())
        sys.exit(1)


main()
